#!/bin/sh

case $1 in
    start)
        /usr/bin/logo-ascii
        ;;

    stop)
        killall logo-ascii
        ;;

    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 [start|stop|restart]"
        ;;
esac
